name: Named-Villagers
main: ovh.paulem.namedvillagers.NamedVillagers
version: ${version}
author: Paulem
description: Gives all villagers a name to enhance your world !
load: STARTUP
website: https://paulem.ovh
api-version: 1.14
softdepend:
  - ProtocolLib